app:
  message: Message sent to the RabbitMQ queue Successfully
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: batch.exchange
    queue: batch.queue
    routingkey: batch.routingkey
  application:
    name: admin-service
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry : true