server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    exchange: batch.exchange
    queue: batch.queue
    routingkey: batch.routingkey
